<thead>
    <tr>
        <th>#</th>
        <th>@lang("messages.week.L")</th>
        <th>@lang("messages.week.M")</th>
        <th>@lang("messages.week.X")</th>
        <th>@lang("messages.week.J")</th>
        <th>@lang("messages.week.V")</th>
    </tr>
</thead>