<x-buttons.basic
    :href="$href"
    :id="$id ?? null"
    :button-class="$class"
    :onclick="$onclick ?? null"
    :target="$target ?? null"
    :rel="$rel ?? null"
    :aria-label="$ariaLabel ?? null"
    :title="$title ?? null"
    :disabled-attr="$disabled ?? ''"
    :data-attrs="$data ?? ''"
    :icon="$icon ?? null"
    :text="$text ?? ''"
    :badge="$badge ?? null"
/>
