@extends('layouts.intranet')
@section('css')
    <title>{{$panel->getTitulo()}}</title>
@endsection
@section('grid')
    @include('lote.partials.grid')
@endsection
@section('titulo')
    {{$panel->getTitulo()}}
@endsection
@section('scripts')
@include('includes.tablesjs')
@endsection
