<?php
return [
    'diaSemana' => [ '1' => 'L','2' => 'M','3' => 'X', '4' => 'J','5' => 'V','6' => 'S','7' => 'D'],
    'estadoMaterial' => ['??','OK','Reparandose','Baja'],
    'actasEnabled' => ['Claustro'=>'Claustro','COCOPE'=>'COCOPE'],
    'procedenciaMaterial' => ['','Dotación','Compra','Donación'],
    'idiomas' => ['es' => 'Español', 'ca' => 'Valencià' , 'en' => 'English'],
    'estadoIncidencia' => ['Rechazada','Pendiente','En proceso','Resuelta'],
    'estadoOrden' => ['Abierta','Cerrada','Resuelta'],
    'prioridadIncidencia' => ['Baja','Media','Alta'],
    'tipoIncidencia' => [ 1=> 'Qualitat',2=>'Instal.lacions',3=>'Informàtica',4=>'Programari',5=>'FCT'],
    'tipoVehiculo' => ['Avion','Tren','Taxi','Autobus','Otros'],
    'estadoDocumento' => ['Creado','Pendiente','Autorizado','Impreso'],
    'numeracion' => ['--','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15',30=>'AvaIni',31=>'1Ava',32=>'2Ava',33=>'3Ava',34=>'AvFinal',35=>'AvExtr',21=>'1er Trimestre',22=>'2on Trimestre',23=>'Final'],
    'nombreEval' => [1=>'Primera', 2=> 'Segona', 3=>'Final', 4=>'Extraordinària'],
    'tipoExpediente' => [   1=>'Baixa Inasistència',
                            2=>'Pèrdua Avaluació Continua',
                            4=>"Remisió al departament d'Orientació",
                            5=>"Part d'amonestació"
     ],
    'asociacionEmpresa' => [1=>'FCT',2=>'FCT Convalidada/Exempció'],
    'grupoTutoria' => [0=>'Tots el grups',1=>'Grau mitjà',2=>'Grau Superior'],
    'motivoAusencia' => ['Baja médica', 'Licencia por formación', 'Enfermedad común', 'Traslado de domicilio', 'Asistencia pruebas selectivas', 'Enfermedad grave o muerte del cónyuge', 'Asistencia médica, educativa o asistencial', 'Otros (rellenar cuadro de observaciones)'],
    'tipoEstudio' => [1=>'Cicle Formatiu de Grau Mitjà','2'=>'Cicle Formatiu de Grau Superior','3'=>'Cicle Formatiu Bàsic','4'=>'Batxiller','5'=>'ESO','6'=>'Primària'],
    'tipoEstudioC' => [1=>'Ciclo Formativo de Grado Medio','2'=>'Ciclo Formativo de Grado Superior','3'=>'Ciclo Formativo Básico','4'=>'Bachiller','5'=>'ESO','6'=>'Primaria'],
    'tipoTutoria' => [0=>'No assignada',1=>'Xarrades Programades',2=>'Convivència',3=>'Acadèmiques-Professionals',4=>'Temes transversals'],
    'veep' => [],
    'estadoColaboracion' => [0=>'',1=>'??',2=>'Col·labora',3=>'No col·labora'],
    'incidenciasColaboracion' => [1=>'Envia correu contacte',2=>'Envia confirmació de dades',3=>"Envia documentació d'inici",4=>"Denegació pràctiques",5=>'Comentari Professor',6=>'Comentari Instructor',7=>'Telefònic'],
    'reunionesControlables' => [2, 5, 6, 7, 9],
    'who' => [1=>'Alumno',2=>'Profesor'],
    'what' => [1=>'--',2=>'Profesor',3=>'Actividad',4=>'Fct'],

];