<?php
return
[   'partAmonestacio' => ['codi' => 'F1.PC01' , 'edicio' => '00'],
    'memoriaDepartament' => ['codi' => 'F3.PC02' , 'edicio' => '00'],
    'actaReunio' => ['codi' => 'F4.PC02', 'edicio' => '00'],
    'actaAvaluacio' => ['codi' => 'F5.PC02' ,'edicio' => '00'],
    'actaFSE' => ['codi' => 'F6.PC02' , 'edicio' => '00'],
    'actaDelegat' => ['codi' => 'F7.PC02' , 'edicio' => '00'],
    'autoritzacioMenors' => ['codi' => 'F10.PC02', 'edicio' => '00'],
    'extraescolars' => ['codi' => 'F18.PC02' ,'edicio' => '00'],
    'baixaInasistencia' => ['codi' => 'F11.PC02' , 'edicio' => '00'],
    'perdidaContinua' => ['codi' => 'F12.PC02' , 'edicio' => '00'],
    'actaProyecto' => ['codi' => 'F14.PC02', 'edicio' => '00'],
    'actaDefensa' => ['codi' => 'F15.PC02' ,'edicio' => '00'],
    'comisionsServei' => ['codi' => 'F2.PC04' , 'edicio' => '00'],
    'controlServei' => ['codi' => 'F4.PC04', 'edicio' => '01'],
    'seguimentInstructor' => ['codi' => 'F5.PC04' ,'edicio' => '00'],
    'seguimentAlumnes' => ['codi' => 'F6.PC04' ,'edicio' => '00'],
    'fullVacances' => ['codi' => 'F7.PC04' ,'edicio' => '00'],
    'comunicacioAbsencia' => ['codi' => 'F1.PS04' ,'edicio' => '00'],
    'comunicacioBirret' => ['codi' => 'F2.PS04' ,'edicio' => '00'],
    'certificatsFCT' => ['codi' => 'F3.PC04' , 'edicio' => '00'],
    'certificatInstructor' => ['codi' => 'F3.PC04' , 'edicio' => '00'],
    'certificatRiscos' => ['codi' => '' ,'edicio' => '00','vista'=>''],

];
