<?php


return [
        'delete' => 'fa-eraser',
        'edit' => 'fa-edit',
        'read' => 'fa-eyedropper',
        'authorize' => 'fa-smile-o',
        'unauthorize' => 'fa-frown-o',
        'process' => 'fa-smile-o',
        'noprocess' => 'fa-frown-o',
        'show' => 'fa-eye',
        'detalle' => 'fa-plus-square',
        'carnet' => 'fa-credit-card',
        'refuse' => 'fa-remove',
        'resolve' => 'fa-smile-o',
        'pdf' => 'fa-file-pdf-o',
        'autorizacion' => 'fa-file-pdf-o',
        'email' => 'fa-envelope',
        'init' => 'fa-envelope',
        'notification' => 'fa-bell',
        'active' => 'fa-check',
        'horario' => 'fa-table',
        'copy' => 'fa-copy',
        'muestra' => 'fa-image',
        'justify' => 'fa-thumbs-o-up',
        'baja' => 'fa-remove',
        'register' => 'fa-thumbs-o-up',
        'unregister' => 'fa-thumbs-o-down',
        'cancel' => 'fa-times',
        'document' => 'fa-file',
        'unpaid' => 'fa-money',
        'saveFile' => 'fa-send',
        'anexo' => 'fa-plus',
        'up' => 'fa-arrow-up',
        'down' => 'fa-arrow-down',
        'orden' => 'fa-calendar',
        'open' => 'fa-toggle-on',
    ];