<?php
return [
    'rol' => [
        'direccion' => 2,
        'jefe_dpto' => 13,
        'tutor' => 17,
        'mantenimiento' => 7,
        'profesor' => 3,
        'alumno' => 5,
        'administrador' => 11,
        'todos' => 1,
        'conserge' => 23,
        'orientador' => 29,
        'practicas' => 31,
        'convivencia' => 37,
        'jefe_practicas' => 41,
        'qualitat' => 43,
        'comissio_IiC' => 47
    ],
    'lor' => [
        2 => 'direccion',
        13 => 'jefe_dpto',
        17 => 'tutor',
        7 => 'mantenimiento',
        3 => 'profesor',
        11 => 'administrador',
        23 => 'conserge',
        29 => 'orientador',
        5 => 'alumno',
        1 => 'todos',
        31 => 'practicas',
        37 => 'convivencia',
        41 => 'jefe_practicas',
        43 => 'qualitat',
        47 => 'comissio_IiC',
    ],
    'actions' => [
        'SegAval' => 'Seguiments Avaluació',
        'ActAval' => "Acta d'avaluació",
        'ActaFSE' => "Acta Fons Social Europeu",
        'ActaDel' => "Acta d'elecció de delegat",
        'InfDept' => 'Informe departament',
        'AvalPrg' => 'Avaluació de la programació',
        'EntrPrg' => 'Entrega de la programació',
        'AprAval' => 'Aprovació de programacions'
    ]];
